services:
  projectvg-memory-server:
    build: .
    ports:
      - "5602:5602"
    depends_on:
      - qdrant
    environment:
      # 서버 설정
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - SERVER_PORT=5602
      - SERVER_HOST=0.0.0.0
      # 로깅 설정
      - LOG_LEVEL=INFO
      - LOG_FILE=
      # OpenAI 설정 (환경변수로 덮어쓰기 가능)
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # .env 파일에서 필수로 설정
      - OPENAI_MODEL_NAME=text-embedding-3-small
      - OPENAI_VECTOR_DIMENSION=1536
      - OPENAI_USER_IDENTIFIER=memory_server_v2
      # 컬렉션 벡터 차원 설정
      - EPISODIC_VECTOR_DIM=1536
      - SEMANTIC_VECTOR_DIM=1536
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - projectvg-network
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - projectvg_memory_data:/qdrant/storage
    networks:
      - projectvg-network
    restart: unless-stopped

volumes:
  projectvg_memory_data:

networks:
  projectvg-network:
    driver: bridge 